"""Added Role model

Revision ID: 1aba310bd3fc
Revises: 6658234171dd
Create Date: 2024-07-15 21:31:24.016707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aba310bd3fc'
down_revision = '6658234171dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_info_email_gp', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_info_email_gp', ['email_gp'])

    # ### end Alembic commands ###
