"""Add foreign key relationship between StudentInfo and User

Revision ID: 6658234171dd
Revises: e086f0f417ef
Create Date: 2024-07-15 05:01:16.378136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6658234171dd'
down_revision = 'e086f0f417ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.create_foreign_key('fk_student_info_user_email', 'user', ['email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_info_user_email', type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
