"""Updated models with relationships

Revision ID: 765fbf94b8e3
Revises: 7ee818a3e4ea
Create Date: 2024-08-06 00:41:56.274762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765fbf94b8e3'
down_revision = '7ee818a3e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_announcement')
    
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_student_info_email', ['email'])
        batch_op.drop_constraint('fk_student_info_user_email', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_student_info_user_email',  # Constraint name
            'user', 
            ['email'], 
            ['email']
        )
        batch_op.drop_constraint('uq_student_info_email', type_='unique')
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_announcement',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=150), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=False),
        sa.Column('created_by', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_tmp_announcement_created_by'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
