"""Change date_of_birth to VARCHAR

Revision ID: de13624e5514
Revises: 81cd70b2dcf2
Create Date: 2024-07-15 22:44:03.832954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de13624e5514'
down_revision = '81cd70b2dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_student_info')
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('fk_student_info_user_email', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_student_info_user_email', 'user', ['email'], ['email'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    op.create_table('_alembic_tmp_student_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('parent_guardian_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('relationship_to_student', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('emergency_relationship', sa.VARCHAR(length=100), nullable=False),
    sa.Column('emergency_contact_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email_gp', sa.VARCHAR(length=150), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_student_info_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
