"""Add email_gp field to StudentInfo model

Revision ID: e086f0f417ef
Revises: a77a117a3569
Create Date: 2024-07-15 03:11:54.731907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e086f0f417ef'
down_revision = 'a77a117a3569'
branch_labels = None
depends_on = None


def upgrade():
    # Commands auto generated by Alembic - please adjust as needed
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_gp', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint('uq_student_info_email_gp', ['email_gp'])

def downgrade():
    # Commands auto generated by Alembic - please adjust as needed
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_info_email_gp', type_='unique')
        batch_op.drop_column('email_gp')